---
title: "clustering-with-gmm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{clustering-with-gmm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(greed)
library(ggplot2)
library(tidyr)
library(tibble)
```


```{r data-generation,fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
crux = function(N,m,noise){
  x1 = rnorm(N/2)
  x2 = rnorm(N/2)
  X = rbind(cbind(x1,x1+rnorm(N/2)*noise),cbind(x2,-x2+rnorm(N/2)*noise))
  X+rep(m,each=N)
}
Ng = 300
noise=0.2
X=rbind(crux(Ng,c(-10,10),noise),
        crux(Ng,c(-10,-10),noise),
        crux(Ng,c(10,-10),noise),
        crux(Ng,c(10,10),noise))
ggplot(tibble(x=X[,1],y=X[,2]))+
  geom_point(aes(x=x,y=y))+
  theme_bw()
```

```{r first try,fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
sol=greed(X)
ggplot(tibble(x=X[,1],y=X[,2],col=factor(sol@cl,levels=1:max(sol@cl))))+
  geom_point(aes(x=x,y=y,color=col))+
  theme_bw()
```

```{r second-try,fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
model = new("gmm",N0=ncol(X),epsilon=0.1*cov(X)/ncol(X),mu=apply(X,2,mean),tau=0.001)
sol=greed(X,model=model,alg=new("hybrid",pop_size=40))
ggplot(tibble(x=X[,1],y=X[,2],col=factor(sol@cl,levels=1:max(sol@cl))))+
  geom_point(aes(x=x,y=y,color=col))+
  theme_bw()
```

```{r real-data,fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
library(MASS)
data(crabs)
X=as.matrix(crabs[,4:8])
model = new("gmm",N0=ncol(X),epsilon=cov(X),mu=apply(X,2,mean),tau=0.001)
sol=greed(X,model=model,alg=new("hybrid",pop_size=40))
table(paste(crabs[,1],crabs[,2],sep = "-"),sol@cl)
```




