---
title: "Latent Class Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Latent Class Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
Loads packages.
```{r setup,message=FALSE}
library(readr)
library(dplyr)
library(stringr)
library(careless)
library(ggrepel)
library(greed)
library(ggplot2)
#https://www.kaggle.com/miroslavsabo/young-people-survey
#survey=read_csv("data-raw/responses.csv")
data("Youngpeoplesurvey")
```


```{r,cache=TRUE}
nc  = 19

selected = Youngpeoplesurvey %>% 
  select(all_of(1:nc)) %>%
  mutate(string = longstring(.)) %>%
  mutate(sel = if_else(string <= 10,TRUE,FALSE) ) %>% pull(sel)

Xnum = Youngpeoplesurvey %>% 
  select(all_of(1:nc)) %>%
  filter(all_of(selected) )
X = Xnum %>% 
  mutate_all(\(x){factor(x,levels=1:5)}) %>% 
  droplevels()

```

```{r survey-lca-cust,cache=TRUE, fig.show='hold',out.width="100%",fig.width=8,fig.height=5.5}
set.seed(31)
library(future)
plan(multisession)
sol=greed(X)
plot(sol,type='tree')
```



```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
table(sol@cl)
ncut = 3
solf=cut(sol, ncut)
```

```{r posplot, fig.show='hold',fig.width=8,fig.height=12,out.width="100%"}
params = coef(solf)
means_scores = lapply(params$Thetak,\(x){apply(x,1,\(r){sum(r*as.numeric(names(r)))})})
means_scores_long = do.call(rbind,purrr::map2(means_scores,names(means_scores),\(x,y){tibble(cluster=names(x),mean=x,var=y)}))  %>% mutate(var = gsub("\\."," ",var))

means_scores_glob = Xnum %>% 
  summarise_all(\(x){mean(x,na.rm=TRUE)}) %>% 
  tidyr::pivot_longer(1:nc,names_to = "var",)%>% 
  mutate(var = gsub("[,-/]"," ",var))

gg = means_scores_long %>% 
  left_join(means_scores_glob) %>% 
  mutate(dm=mean-value) 

cluster_profile = function(clid){
  df = gg %>% filter(cluster==paste0("cluster",clid)) %>% arrange(desc(abs(dm))) %>% head(25)
  ggplotGrob(ggplot(df)+
    geom_text_repel(aes(x=0,y=dm,size=abs(dm),color=dm,label=var),
                    direction="x",
                    min.segment.length = 800,    
                    force_pull    = 0,
                    max.time      = 0.5,
                    max.iter      = 1e5,
                    max.overlaps  = Inf,
                    segment.color = NA,
                    point.padding = NA)+
    scale_color_gradient2(guide="none")+
    scale_size_area(guide="none",max_size = 3)+
    theme_minimal()+
    scale_x_discrete("",breaks=c(),expand = c(0.2,1))+
    scale_y_continuous("cluster score difference with average",limits = c(-1.5,1.5))+
    ggtitle(paste("Cluster",clid),subtitle = paste(round(params$pi[clid]*100),"% of the respondents")))
}

plts_list = lapply(1:ncut,\(cli){cluster_profile(cli)})


grid::grid.draw(gridExtra::arrangeGrob(grobs=plts_list, nrow = ncut,ncol = 1))

```


```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
res.mca <- FactoMineR::MCA(X, graph = FALSE)
factoextra::fviz_mca_ind(res.mca,
             label = "none", # masquer le texte des individus
             habillage = solf@cl, # colorer par groupes
             # palette = c ("#00AFBB", "#E7B800"),
             addEllipses = TRUE, ellipse.type = "confidence",
             ggtheme = theme_minimal ())
```


```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
table(Youngpeoplesurvey$Gender[selected],solf@cl)
```



```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
table(Youngpeoplesurvey$Education[selected],solf@cl)
```


```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
table(Youngpeoplesurvey$`House - block of flats`[selected],solf@cl)
```


```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
table(Youngpeoplesurvey$`Village - town`[selected],solf@cl)
```

```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
table(Youngpeoplesurvey$Smoking[selected],solf@cl)
```


```{r, fig.show='hold',out.width="60%",fig.width=8,fig.height=6}
table(Youngpeoplesurvey$Alcohol[selected],solf@cl)
```