---
title: "missingdata"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{missingdata}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(greed)
library(missSBM)
library(dplyr)
library(ggplot2)
```


```{r sim1,message=FALSE,results='hide',fig.width=6}
# simu params 
epsi = 0.05
N=100
mu = list(mean=(diag(3)*(1-epsi)) + (matrix(1,3,3)-diag(3))*epsi)
Nbsim = 25
p0 = 0.2
p1 = 0.5


# to store greed res
Kh = rep(0,Nbsim)
NMIh = rep(0,Nbsim)
ARIh = rep(0,Nbsim)
# for vem
Kms = rep(0,Nbsim)
NMIms = rep(0,Nbsim)
ARIms = rep(0,Nbsim)

for (isim in 1:Nbsim){
  # simulate data
  sbm = sbm::sampleSimpleSBM(N,c(1/3,1/3,1/3),mu)
  X=sbm$networkData
  Xo = observeNetwork(X,"double-standard",c(p0,p1))
  #Xc = to_multinomial(Xo)
  
  # greed
  sol=greed(Xo)
  Kh[isim]=sol@K
  NMIh[isim]=NMI(sbm$memberships,sol@cl)
  ARIh[isim]=aricode::ARI(sbm$memberships,sol@cl)
  
  # vem
  ms=estimateMissSBM(Xo,vBlocks = 1:10,sampling="double-standard")
  Kms[isim]=ms$bestModel$fittedSBM$nbBlocks
  NMIms[isim]=NMI(sbm$memberships,ms$bestModel$fittedSBM$memberships)
  ARIms[isim]=aricode::ARI(sbm$memberships,ms$bestModel$fittedSBM$memberships)
}
# plot
res = tibble(ari=ARIh,nmi=NMIh,K=Kh,alg="greed") %>% bind_rows(tibble(ari=ARIms,nmi=NMIms,K=Kms,alg="vem"))
ggplot(res)+geom_boxplot(aes(y=nmi,x=alg))+geom_jitter(aes(y=nmi,x=alg))
ggplot(res)+geom_boxplot(aes(y=ari,x=alg))+geom_jitter(aes(y=ari,x=alg))
ggplot(res)+geom_bar(aes(x=K))+facet_wrap(~alg)+scale_x_continuous(breaks=1:10,labels=1:10)
```


```{r sim2,message=FALSE,results='hide',fig.width=6}
# simu params plus dur
epsi = 0.05
N=100
mu = list(mean=(diag(3)*(1-epsi)) + (matrix(1,3,3)-diag(3))*epsi)
Nbsim = 25
p0=0.1
p1=0.2
# to store greed res
Kh = rep(0,Nbsim)
NMIh = rep(0,Nbsim)
ARIh = rep(0,Nbsim)
# for vem
Kms = rep(0,Nbsim)
NMIms = rep(0,Nbsim)
ARIms = rep(0,Nbsim)

for (isim in 1:Nbsim){
  # simulate data
  sbm = sbm::sampleSimpleSBM(N,c(1/3,1/3,1/3),mu)
  X=sbm$networkData
  Xo = observeNetwork(X,"double-standard",c(p0,p1))
  #Xc = to_multinomial(Xo)
  
  # greed
  sol=greed(Xo)
  Kh[isim]=sol@K
  NMIh[isim]=NMI(sbm$memberships,sol@cl)
  ARIh[isim]=aricode::ARI(sbm$memberships,sol@cl)
  
  # vem
  ms=estimateMissSBM(Xo,vBlocks = 1:10,sampling="double-standard")
  ms
  Kms[isim]=ms$bestModel$fittedSBM$nbBlocks
  NMIms[isim]=NMI(sbm$memberships,ms$bestModel$fittedSBM$memberships)
  ARIms[isim]=aricode::ARI(sbm$memberships,ms$bestModel$fittedSBM$memberships)
}
# plot
res = tibble(ari=ARIh,nmi=NMIh,K=Kh,alg="greed") %>% bind_rows(tibble(ari=ARIms,nmi=NMIms,K=Kms,alg="vem"))
ggplot(res)+geom_boxplot(aes(y=nmi,x=alg))+geom_jitter(aes(y=nmi,x=alg))
ggplot(res)+geom_boxplot(aes(y=ari,x=alg))+geom_jitter(aes(y=ari,x=alg))
ggplot(res)+geom_bar(aes(x=K))+facet_wrap(~alg)+scale_x_continuous(breaks=1:10,labels=1:10)
```




```{r sim3,message=FALSE,results='hide',fig.width=6}
# simu params une facile 
epsi = 0.05
N=100
mu = list(mean=(diag(3)*(1-epsi)) + (matrix(1,3,3)-diag(3))*epsi)
Nbsim = 10
p0 = seq(0.05,0.4,length.out = 20)
p1 = 0.1

# to store greed res
Kh = matrix(0,20,Nbsim)
NMIh = matrix(0,20,Nbsim)
ARIh = matrix(0,20,Nbsim)
# for vem
Kms = matrix(0,20,Nbsim)
NMIms = matrix(0,20,Nbsim)
ARIms = matrix(0,20,Nbsim)


for(i in 1:length(p0)){
for (isim in 1:Nbsim){
  # simulate data
  sbm = sbm::sampleSimpleSBM(N,c(1/3,1/3,1/3),mu)
  X=sbm$networkData
  Xo = observeNetwork(X,"double-standard",c(p0[i],p1))
  #Xc = to_multinomial(Xo)
  
  # greed
  sol=greed(Xo)
  Kh[i,isim]=sol@K
  NMIh[i,isim]=NMI(sbm$memberships,sol@cl)
  ARIh[i,isim]=aricode::ARI(sbm$memberships,as.vector(sol@cl))
  
  # vem
  ms=estimateMissSBM(Xo,vBlocks = 1:10,sampling="double-standard")
  ms
  Kms[i,isim]=ms$bestModel$fittedSBM$nbBlocks
  NMIms[i,isim]=NMI(sbm$memberships,ms$bestModel$fittedSBM$memberships)
  ARIms[i,isim]=aricode::ARI(sbm$memberships,ms$bestModel$fittedSBM$memberships)
}
}
```


```{r sim3plot,message=FALSE,results='hide',fig.width=6}
# plot
res = tibble(ari=as.vector(ARIh),nmi=as.vector(NMIh),K=as.vector(Kh),p0=rep(p0,Nbsim),alg="greed") %>% bind_rows(tibble(ari=as.vector(ARIms),nmi=as.vector(NMIms),K=as.vector(Kms),p0=rep(p0,Nbsim),alg="vem"))
ggplot(res %>% group_by(alg,p0) %>% summarise(nmi=mean(nmi)))+geom_line(aes(x=p0,y=nmi,color=alg))
ggplot(res)+geom_boxplot(aes(y=ari,x=p0,group=p0))+facet_wrap(~alg)
```

```{r sim4,message=FALSE,fig.width=6, cache=TRUE}
# simulate gros graph
sbm = sbm::sampleSimpleSBM(2000,c(1/3,1/3,1/3),mu)
X   = sbm$networkData
Xo  = observeNetwork(X,"double-standard",c(0.01,0.05))
sol=greed(Xo)
table(sol@cl,sbm$memberships)
```


