---
title: "Mixture of regression"
author: "Etienne Côme"
date: "`r Sys.Date()`"
fig_caption: yes
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Graph clustering with SBM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


Loads packages and set a future plan for parallel processing.
```{r}
library(future)
library(Matrix)
library(ggplot2)
library(greed)
plan(multisession)
mat_reg_line = function(x,Xd,yd){
  K = length(x@obs_stats$counts)
  D = length(x@obs_stats$regs[[1]]$mu)
  ggp= data.frame(x=Xd[,1],y=yd,K=factor(x@cl,levels=1:K))
  gg=data.frame(y=as.vector(cbind(seq(min(ggp$x),max(ggp$x),length.out = 20),rep(1,20))%*%sapply(x@obs_stats$regs,function(reg){reg$mu})),
                x=rep(seq(min(ggp$x),max(ggp$x),length.out = 20),K),K=rep(1:K,each=20))
  ggplot2::ggplot()+
    ggplot2::geom_point(data=ggp[,1:2],ggplot2::aes(x=x,y=y),alpha=0.05)+
    ggplot2::geom_path(data=gg,ggplot2::aes(x=x,y=y,group=K))+
    ggplot2::geom_point(data=ggp,ggplot2::aes(x=x,y=y,col=K))+
    ggplot2::ggtitle(paste0("Mixture of Regression Model with : ",max(x@cl)," clusters."))+
    ggplot2::facet_wrap(~K)+
    ggplot2::theme_bw()      
}
```

Simulation 
```{r, fig.show='hold'}
N=800
K=3
pi=rep(1/K,K)
sig = 0.1
mu = matrix(rnorm(K*K),K,K)*0.3
diag(mu)=1
mre = rmreg(N,pi,mu,sig)
gg = data.frame(x=mre$X[,1],y=mre$y)
ggplot(gg)+geom_point(aes(x=x,y=y,col=factor(mre$cl)))
```

Perform the clustering with default model and algorithm. An sbm model is used for squared matrix and a genetic algorithm is selected by default. The second parameter is just an itnitial guess for the number of cluster.

```{r}
sol = greed_cond(mre$X,mre$y/sd(mre$y),model=new("mreg",reg=0.1))
```

```{r, fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
plot(sol,type='tree')
```

Plot the results with a front diagram
```{r, fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
plot(sol,type='front')
```

```{r, fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
table(sol@cl,mre$cl)
```

```{r, fig.show='hold'}
N=800
K=2
pi=rep(1/K,K)
sig = 0.1
mu = matrix(rnorm(K*2),2,K)
mre = rmreg(N,pi,mu,sig)
gg = data.frame(x=mre$X[,1],y=mre$y)
ggplot(gg)+geom_point(aes(x=x,y=y,col=factor(mre$cl)))
```

```{r, fig.show='hold'}
sol = greed_cond(mre$X,mre$y/sd(mre$y),model=new("mreg",reg=0.1))
mat_reg_line(sol,mre$X,mre$y/sd(mre$y))
```


```{r, fig.show='hold'}
probs=post_probs(new("mreg",reg=0.1),list(X=mre$X,y=mre$y/sd(mre$y)),sol@cl)
entropy=apply(probs,1,function(p){-sum(p*log(p))})
pm=apply(probs,1,function(p){max(p)})
ggp = data.frame(entropy=entropy,x=mre$X[,1],y=mre$y/sd(mre$y),pm=pm) 
ggp = ggp[order(ggp$pm),]
ggplot(ggp)+
  geom_point(aes(x=x,y=y,color=pm))+
  scale_color_distiller(palette="YlOrRd")
```


```{r, fig.show='hold'}
ggplot(ggp)+
  geom_point(aes(x=x,y=y,color=pm))+
  scale_color_distiller(palette="YlOrRd")
```