---
title: "Count data clustering with the Mixture of Multinomials model"
author: "Etienne Côme & Nicolas Jouvin"
output: 
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Count data clustering with the Mixture of Multinomials model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE, message=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
Loads packages.
```{r setup, include=TRUE, message=FALSE}
library(future) # allows parralel processing in greed()
library(greed)
library(mclust)
library(ggplot2)
set.seed(2134)

future::plan("multisession", workers=2) # may be increased 
```


# In construction
Dummy example with 3 variables.
```{r}
help("MoM")
```

```{r , eval=FALSE}
K=2
mu = matrix(c(0.1, 0.7, 0.2, 0.8, 0.1, 0.1), byrow = T, nrow = 2, ncol = 3)
N=500
simu <- rmm(N=N, pi=rep(1/K, K), mu = mu, lambda = rep(200, N))
model = MoM(alpha = 1, beta = 1)
sol = greed(X = simu$x, model=model, alg = Hybrid())
table(simu$cl, clustering(sol))
```