---
title: "Graph clustering with SBM"
author: "Etienne Côme"
date: "`r Sys.Date()`"
fig_caption: yes
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Graph clustering with SBM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



```{r}
library(Matrix)
library(ggplot2)
library(greed)
library(dplyr)
```

Load data and set seed for correct labels
```{r, fig.show='hold'}
set.seed(32)
data("Xpol")
```

clustering 

```{r}
sol = greed(Xpol,25,model=new("dcsbm"),alg=new("hybrid",pop_size=50))
```


Results

```{r, fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
plot(sol)
```
Plot the results with a node link diagram.
```{r, fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
plot(sol,type='tree')
```
Or a dendogram for sleecting a smaller value for K.
```{r, fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
probs = post_probs(new("dcsbm"),list(X=Xpol),sol@cl)
rl=data.frame(size=colnames(Xpol),cl=sol@cl,dout=rowSums(Xpol),din=colSums(Xpol),p=apply(probs,1,max))
rl %>% group_by(cl) %>% top_n(3,din) %>% arrange(cl)
```
Eventually study the evolution of $-log(\alpha)$ with respect to $K$.
```{r, fig.show='hold',out.width="70%",fig.width=15,fig.height=9.5}
labels=c("Media Ref","Media","PQR","Media + G","Gauche","Buzz / Télé","RT / Atl / Sput","Ext / Droite","Pseudo-Science","Alt / Comp", "Alt / Comp","Presse / Alt")
nodelinklab(sol,labels,10)
```

And select a smaller value to extract a new solution.
```{r, fig.show='hold',out.width="70%",fig.width=8,fig.height=5.5}
graphbalance(sol)
```
