// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// init
S4 init(S4 model, arma::sp_mat& xp, arma::vec& clt);
RcppExport SEXP _greed_init(SEXP modelSEXP, SEXP xpSEXP, SEXP cltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type clt(cltSEXP);
    rcpp_result_gen = Rcpp::wrap(init(model, xp, clt));
    return rcpp_result_gen;
END_RCPP
}
// fit_greed
S4 fit_greed(S4 model, arma::sp_mat& xp, int Ki, std::string type, int nb_max_pass, bool verbose);
RcppExport SEXP _greed_fit_greed(SEXP modelSEXP, SEXP xpSEXP, SEXP KiSEXP, SEXP typeSEXP, SEXP nb_max_passSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type Ki(KiSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type nb_max_pass(nb_max_passSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_greed(model, xp, Ki, type, nb_max_pass, verbose));
    return rcpp_result_gen;
END_RCPP
}
// fit_greed_init
S4 fit_greed_init(S4 model, arma::sp_mat& xp, arma::vec& clt, std::string type, int nb_max_pass, bool verbose);
RcppExport SEXP _greed_fit_greed_init(SEXP modelSEXP, SEXP xpSEXP, SEXP cltSEXP, SEXP typeSEXP, SEXP nb_max_passSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type clt(cltSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type nb_max_pass(nb_max_passSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_greed_init(model, xp, clt, type, nb_max_pass, verbose));
    return rcpp_result_gen;
END_RCPP
}
// fit_greed_path
S4 fit_greed_path(arma::sp_mat& xp, S4 init);
RcppExport SEXP _greed_fit_greed_path(SEXP xpSEXP, SEXP initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< S4 >::type init(initSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_greed_path(xp, init));
    return rcpp_result_gen;
END_RCPP
}
// init_cond
S4 init_cond(S4 model, arma::mat& X, arma::colvec& y, arma::vec& clt);
RcppExport SEXP _greed_init_cond(SEXP modelSEXP, SEXP XSEXP, SEXP ySEXP, SEXP cltSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type clt(cltSEXP);
    rcpp_result_gen = Rcpp::wrap(init_cond(model, X, y, clt));
    return rcpp_result_gen;
END_RCPP
}
// fit_greed_cond
S4 fit_greed_cond(S4 model, arma::mat& X, arma::colvec& y, int Ki, std::string type, int nb_max_pass, bool verbose);
RcppExport SEXP _greed_fit_greed_cond(SEXP modelSEXP, SEXP XSEXP, SEXP ySEXP, SEXP KiSEXP, SEXP typeSEXP, SEXP nb_max_passSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type Ki(KiSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type nb_max_pass(nb_max_passSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_greed_cond(model, X, y, Ki, type, nb_max_pass, verbose));
    return rcpp_result_gen;
END_RCPP
}
// fit_greed_init_cond
S4 fit_greed_init_cond(S4 model, arma::mat& X, arma::colvec& y, arma::vec& clt, std::string type, int nb_max_pass, bool verbose);
RcppExport SEXP _greed_fit_greed_init_cond(SEXP modelSEXP, SEXP XSEXP, SEXP ySEXP, SEXP cltSEXP, SEXP typeSEXP, SEXP nb_max_passSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type clt(cltSEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type nb_max_pass(nb_max_passSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_greed_init_cond(model, X, y, clt, type, nb_max_pass, verbose));
    return rcpp_result_gen;
END_RCPP
}
// fit_greed_path_cond
S4 fit_greed_path_cond(arma::mat& X, arma::colvec& y, S4 init);
RcppExport SEXP _greed_fit_greed_path_cond(SEXP XSEXP, SEXP ySEXP, SEXP initSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< S4 >::type init(initSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_greed_path_cond(X, y, init));
    return rcpp_result_gen;
END_RCPP
}
// lm_post
List lm_post(const arma::mat X, const arma::colvec& y, double regu, double a0, double b0);
RcppExport SEXP _greed_lm_post(SEXP XSEXP, SEXP ySEXP, SEXP reguSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type regu(reguSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(lm_post(X, y, regu, a0, b0));
    return rcpp_result_gen;
END_RCPP
}
// lm_post_add
List lm_post_add(List current, const arma::mat X, const arma::colvec& y, double regu, double a0, double b0);
RcppExport SEXP _greed_lm_post_add(SEXP currentSEXP, SEXP XSEXP, SEXP ySEXP, SEXP reguSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type current(currentSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type regu(reguSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(lm_post_add(current, X, y, regu, a0, b0));
    return rcpp_result_gen;
END_RCPP
}
// lm_post_del
List lm_post_del(List current, const arma::mat X, const arma::colvec& y, double regu, double a0, double b0);
RcppExport SEXP _greed_lm_post_del(SEXP currentSEXP, SEXP XSEXP, SEXP ySEXP, SEXP reguSEXP, SEXP a0SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type current(currentSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type regu(reguSEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(lm_post_del(current, X, y, regu, a0, b0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_greed_init", (DL_FUNC) &_greed_init, 3},
    {"_greed_fit_greed", (DL_FUNC) &_greed_fit_greed, 6},
    {"_greed_fit_greed_init", (DL_FUNC) &_greed_fit_greed_init, 6},
    {"_greed_fit_greed_path", (DL_FUNC) &_greed_fit_greed_path, 2},
    {"_greed_init_cond", (DL_FUNC) &_greed_init_cond, 4},
    {"_greed_fit_greed_cond", (DL_FUNC) &_greed_fit_greed_cond, 7},
    {"_greed_fit_greed_init_cond", (DL_FUNC) &_greed_fit_greed_init_cond, 7},
    {"_greed_fit_greed_path_cond", (DL_FUNC) &_greed_fit_greed_path_cond, 3},
    {"_greed_lm_post", (DL_FUNC) &_greed_lm_post, 5},
    {"_greed_lm_post_add", (DL_FUNC) &_greed_lm_post_add, 6},
    {"_greed_lm_post_del", (DL_FUNC) &_greed_lm_post_del, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_greed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
