// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fit_icl
List fit_icl(S4 model, arma::sp_mat& xp, int Ki);
RcppExport SEXP _greed_fit_icl(SEXP modelSEXP, SEXP xpSEXP, SEXP KiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type model(modelSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type xp(xpSEXP);
    Rcpp::traits::input_parameter< int >::type Ki(KiSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_icl(model, xp, Ki));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_greed_fit_icl", (DL_FUNC) &_greed_fit_icl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_greed(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
