# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' post_probs
#' @param model icl_model
#' @param data list with clustering data (fileds depend on model type)
#' @param clt cluster labels in 1,..,K
#' @export
post_probs <- function(model, data, clt) {
    .Call('_greed_post_probs', PACKAGE = 'greed', model, data, clt)
}

#' fit_greed
#' @param model icl_model
#' @param data list with clustering data (fileds depend on model type)
#' @param clt cluster labels {0,...,K-1}
#' @param type merge, swap, none, or both (default)  
#' @param nb_max_pass maximum number of pass for greedy swap
#' @param verbose boolean for verbose mode default to false
#' @return a model_fit object  
#' @export
fit_greed_cstr <- function(model, data, clt, iclust, workingset, type = "both", nb_max_pass = 50L, verbose = FALSE) {
    .Call('_greed_fit_greed_cstr', PACKAGE = 'greed', model, data, clt, iclust, workingset, type, nb_max_pass, verbose)
}

merge_cstr <- function(model, data, clt, merge_graph, verbose = FALSE) {
    .Call('_greed_merge_cstr', PACKAGE = 'greed', model, data, clt, merge_graph, verbose)
}

#' fit_greed
#' @param model icl_model
#' @param data list with clustering data (fileds depend on model type)
#' @param clt cluster labels {0,...,K-1}
#' @param type merge, swap, none, or both (default)  
#' @param nb_max_pass maximum number of pass for greedy swap
#' @param verbose boolean for verbose mode default to false
#' @return a model_fit object  
#' @export
fit_greed <- function(model, data, clt, type = "both", nb_max_pass = 50L, verbose = FALSE) {
    .Call('_greed_fit_greed', PACKAGE = 'greed', model, data, clt, type, nb_max_pass, verbose)
}

#' fit_greed_path
#' @param data list with clustering data depnds on model type
#' @param init_fit initial fit object
#' @return a model_path object
#' @export
fit_greed_path <- function(data, init_fit) {
    .Call('_greed_fit_greed_path', PACKAGE = 'greed', data, init_fit)
}

add_sppat <- function(a, b) {
    .Call('_greed_add_sppat', PACKAGE = 'greed', a, b)
}

delcol <- function(a, ci) {
    .Call('_greed_delcol', PACKAGE = 'greed', a, ci)
}

delrowcol <- function(a, ci) {
    .Call('_greed_delrowcol', PACKAGE = 'greed', a, ci)
}

gsum_mm <- function(cl, x, K) {
    .Call('_greed_gsum_mm', PACKAGE = 'greed', cl, x, K)
}

lm_post <- function(X, y, regu, a0, b0) {
    .Call('_greed_lm_post', PACKAGE = 'greed', X, y, regu, a0, b0)
}

lm_post_add1 <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_add1', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

lm_post_del1 <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_del1', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

lm_post_merge <- function(current_k, current_l, regu, a0, b0) {
    .Call('_greed_lm_post_merge', PACKAGE = 'greed', current_k, current_l, regu, a0, b0)
}

lm_post_add <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_add', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

lm_post_del <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_del', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

mvlm_post <- function(X, Y, alpha, N0) {
    .Call('_greed_mvlm_post', PACKAGE = 'greed', X, Y, alpha, N0)
}

mvlm_post_add1 <- function(current, X, Y, alpha, N0) {
    .Call('_greed_mvlm_post_add1', PACKAGE = 'greed', current, X, Y, alpha, N0)
}

mvlm_post_del1 <- function(current, X, Y, alpha, N0) {
    .Call('_greed_mvlm_post_del1', PACKAGE = 'greed', current, X, Y, alpha, N0)
}

mvlm_post_merge <- function(current1, current2, alpha, N0) {
    .Call('_greed_mvlm_post_merge', PACKAGE = 'greed', current1, current2, alpha, N0)
}

