# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

post_probs <- function(model, data, clt) {
    .Call('_greed_post_probs', PACKAGE = 'greed', model, data, clt)
}

fit_greed_cstr <- function(model, data, clt, workingset, iclust, type = "both", nb_max_pass = 50L, verbose = FALSE) {
    .Call('_greed_fit_greed_cstr', PACKAGE = 'greed', model, data, clt, workingset, iclust, type, nb_max_pass, verbose)
}

merge_cstr <- function(model, data, clt, merge_graph, verbose = FALSE) {
    .Call('_greed_merge_cstr', PACKAGE = 'greed', model, data, clt, merge_graph, verbose)
}

swap_cstr <- function(model, data, clt, move_mat, nb_max_pass = 50L, verbose = FALSE) {
    .Call('_greed_swap_cstr', PACKAGE = 'greed', model, data, clt, move_mat, nb_max_pass, verbose)
}

fit_greed <- function(model, data, clt, type = "both", nb_max_pass = 50L, verbose = FALSE) {
    .Call('_greed_fit_greed', PACKAGE = 'greed', model, data, clt, type, nb_max_pass, verbose)
}

fit_greed_path <- function(data, init_fit) {
    .Call('_greed_fit_greed_path', PACKAGE = 'greed', data, init_fit)
}

merge_mat <- function(data, init_fit) {
    .Call('_greed_merge_mat', PACKAGE = 'greed', data, init_fit)
}

test_swap <- function(model, data, cl, i, newcl) {
    .Call('_greed_test_swap', PACKAGE = 'greed', model, data, cl, i, newcl)
}

test_merge <- function(model, data, cl, k, l) {
    .Call('_greed_test_merge', PACKAGE = 'greed', model, data, cl, k, l)
}

test_merge_correction <- function(model, data, cl, k, l) {
    .Call('_greed_test_merge_correction', PACKAGE = 'greed', model, data, cl, k, l)
}

sp_cross <- function(colvec, rowvec, self, oldcl, newcl, K) {
    .Call('_greed_sp_cross', PACKAGE = 'greed', colvec, rowvec, self, oldcl, newcl, K)
}

add_sppat <- function(a, b) {
    .Call('_greed_add_sppat', PACKAGE = 'greed', a, b)
}

add_spmatpat <- function(a, b) {
    .Call('_greed_add_spmatpat', PACKAGE = 'greed', a, b)
}

which_spmatpat <- function(a, b) {
    .Call('_greed_which_spmatpat', PACKAGE = 'greed', a, b)
}

delcol <- function(a, ci) {
    .Call('_greed_delcol', PACKAGE = 'greed', a, ci)
}

delrowcol <- function(a, ci) {
    invisible(.Call('_greed_delrowcol', PACKAGE = 'greed', a, ci))
}

gsum_mat_sp <- function(cl, x, K) {
    .Call('_greed_gsum_mat_sp', PACKAGE = 'greed', cl, x, K)
}

lm_post <- function(X, y, regu, a0, b0) {
    .Call('_greed_lm_post', PACKAGE = 'greed', X, y, regu, a0, b0)
}

lm_post_add1 <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_add1', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

lm_post_del1 <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_del1', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

lm_post_merge <- function(current_k, current_l, regu, a0, b0) {
    .Call('_greed_lm_post_merge', PACKAGE = 'greed', current_k, current_l, regu, a0, b0)
}

lm_post_add <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_add', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

lm_post_del <- function(current, X, y, regu, a0, b0) {
    .Call('_greed_lm_post_del', PACKAGE = 'greed', current, X, y, regu, a0, b0)
}

mvlm_post_comp <- function(X, Y, M, K, S0, N0) {
    .Call('_greed_mvlm_post_comp', PACKAGE = 'greed', X, Y, M, K, S0, N0)
}

mvlm_post_add1_comp <- function(current, X, Y, M, K, S0, N0) {
    .Call('_greed_mvlm_post_add1_comp', PACKAGE = 'greed', current, X, Y, M, K, S0, N0)
}

mvlm_post_del1_comp <- function(current, X, Y, M, K, S0, N0) {
    .Call('_greed_mvlm_post_del1_comp', PACKAGE = 'greed', current, X, Y, M, K, S0, N0)
}

mvlm_post_merge_comp <- function(current1, current2, M, K, S0, N0) {
    .Call('_greed_mvlm_post_merge_comp', PACKAGE = 'greed', current1, current2, M, K, S0, N0)
}

gmm_marginal <- function(X, tau, N0i, epsilon, mu) {
    .Call('_greed_gmm_marginal', PACKAGE = 'greed', X, tau, N0i, epsilon, mu)
}

gmm_marginal_add1 <- function(current, X, tau, N0i, epsilon, mu) {
    .Call('_greed_gmm_marginal_add1', PACKAGE = 'greed', current, X, tau, N0i, epsilon, mu)
}

gmm_marginal_del1 <- function(current, X, tau, N0i, epsilon, mu) {
    .Call('_greed_gmm_marginal_del1', PACKAGE = 'greed', current, X, tau, N0i, epsilon, mu)
}

gmm_marginal_merge <- function(current1, current2, tau, N0i, epsilon, mu) {
    .Call('_greed_gmm_marginal_merge', PACKAGE = 'greed', current1, current2, tau, N0i, epsilon, mu)
}

possible_moves <- function(k, move_mat) {
    .Call('_greed_possible_moves', PACKAGE = 'greed', k, move_mat)
}

