# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' fit_greed 
#' @param model icl_model
#' @param xp sparseMatrix
#' @param Ki initia guess for K
#' @export
fit_greed <- function(model, xp, Ki) {
    .Call('_greed_fit_greed', PACKAGE = 'greed', model, xp, Ki)
}

#' fit_greed_init
#' @param model icl_model
#' @param xp sparseMatrix
#' @param Ki initia guess for K
#' @param clt luster labels 
#' @export
fit_greed_init <- function(model, xp, Ki, clt) {
    .Call('_greed_fit_greed_init', PACKAGE = 'greed', model, xp, Ki, clt)
}

#' fit_greed 
#' @param xp sparseMatrix
#' @param init initial fit
#' @export
fit_greed_path <- function(xp, init) {
    .Call('_greed_fit_greed_path', PACKAGE = 'greed', xp, init)
}

